// Application-wide constants

export const MAX_REGENERATIONS = 5;

export const JOURNAL_ENTRY_TYPES = [
  "meal_note",
  "personal_note",
  "ketone_reading",
] as const;

// Pagination
export const RECIPES_PAGE_SIZE = 12;
export const JOURNAL_ENTRIES_LIMIT = 50;

// Image compression constants
export const MAX_IMAGE_SIZE_BYTES = 900 * 1024; // 900KB
export const COMPRESSED_IMAGE_MAX_BYTES = 900 * 1024; // 900KB
export const IMAGE_COMPRESSION_QUALITY = 0.8;
export const IMAGE_COMPRESSION_FALLBACK_QUALITY = 0.6;
export const IMAGE_MAX_DIMENSION = 1024;

// Keto diet constants
export const KETO_MAX_CARBS_PER_SERVING = 20; // grams

// South African Cities (Major cities and towns)
export const SOUTH_AFRICAN_CITIES = [
  "Johannesburg",
  "Cape Town",
  "Durban",
  "Pretoria",
  "Port Elizabeth",
  "Bloemfontein",
  "East London",
  "Polokwane",
  "Nelspruit",
  "Kimberley",
  "Rustenburg",
  "Welkom",
  "Pietermaritzburg",
  "Potchefstroom",
  "Klerksdorp",
  "Upington",
  "George",
  "Mossel Bay",
  "Oudtshoorn",
  "Knysna",
  "Stellenbosch",
  "Paarl",
  "Somerset West",
  "Hermanus",
  "Jeffreys Bay",
  "Port Alfred",
  "Grahamstown",
  "Queenstown",
  "Uitenhage",
  "King Williams Town",
  "Butterworth",
  "Mthatha",
  "Newcastle",
  "Ladysmith",
  "Richards Bay",
  "Empangeni",
  "Vryheid",
  "Dundee",
  "Piet Retief",
  "Standerton",
  "Vereeniging",
  "Vanderbijlpark",
  "Sasolburg",
  "Kroonstad",
  "Bethlehem",
  "Harrismith",
  "Phuthaditjhaba",
  "Odendaalsrus",
  "Bothaville",
  "Viljoenskroon",
  "Parys",
  "Vredefort",
  "Heilbron",
  "Frankfort",
  "Villiers",
  "Balfour",
  "Heidelberg",
  "Nigel",
  "Springs",
  "Brakpan",
  "Benoni",
  "Kempton Park",
  "Edenvale",
  "Germiston",
  "Alberton",
  "Orkney",
  "Stilfontein",
  "Hartbeesfontein",
  "Ventersdorp",
  "Coligny",
  "Lichtenburg",
  "Zeerust",
  "Mafikeng",
  "Mmabatho",
  "Vryburg",
  "Kuruman",
  "Kathu",
  "Postmasburg",
  "Danielskuil",
  "Campbell",
  "Griquatown",
  "Prieska",
  "Marydale",
  "Vanwyksvlei",
  "Carnarvon",
  "Williston",
  "Fraserburg",
  "Sutherland",
  "Merweville",
  "Beaufort West",
  "Laingsburg",
  "Ladismith",
  "Calitzdorp",
  "De Rust",
  "Uniondale",
  "Avontuur",
  "Kareedouw",
  "Joubertina",
  "Kruisfontein",
  "Humansdorp",
  "St Francis Bay",
  "Despatch",
  "Kariega",
  "Colchester",
  "Addo",
  "Kirkwood",
  "Paterson",
  "Somerset East",
  "Pearston",
  "Graaff-Reinet",
  "Aberdeen",
  "Middelburg",
  "Cradock",
  "Tarkastad",
  "Hofmeyr",
  "Steynsburg",
  "Venterstad",
  "Aliwal North",
  "Burgersdorp",
  "Jamestown",
  "Barkly East",
  "Lady Grey",
  "Rhodes",
  "Maclear",
  "Ugie",
  "Elliot",
  "Indwe",
  "Cala",
  "Cathcart",
  "Stutterheim",
  "Kei Mouth",
  "Komga",
  "Idutywa",
  "Willowvale",
  "Ngqeleni",
  "Libode",
  "Port St Johns",
  "Lusikisiki",
  "Flagstaff",
  "Bizana",
  "Mount Ayliff",
  "Mount Frere",
  "Matatiele",
  "Cedarville",
  "Underberg",
  "Himeville",
  "Kokstad",
  "Harding",
  "Port Shepstone",
  "Margate",
  "Ramsgate",
  "Southbroom",
  "Port Edward",
  "Shelly Beach",
  "Uvongo",
  "Amanzimtoti",
  "Kingsburgh",
  "Umhlanga",
  "Ballito",
  "Salt Rock",
  "Shakas Rock",
  "Tongaat",
  "Verulam",
  "Phoenix",
  "Chatsworth",
  "Umlazi",
  "Umkomaas",
  "Scottburgh",
  "Park Rynie",
  "Pennington",
  "Ifafa",
  "Umzinto",
  "Umzinto Beach",
  "Hibberdene",
  "Sezela",
  "Umzumbe",
  "Ifafa Beach",
  "Mtwalume",
  "Kelso",
  "Tweni",
] as const;
